<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryVehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryVehicleRepository extends EntityRepository
{
    public function search(array $criteria)
    {
        $result = $this->createQueryBuilder('countryVehicle');

        if (!empty($criteria['vehicle']))
        {
            $result->andWhere('countryVehicle.vehicle = :vehicle')
                ->setParameter('vehicle', $criteria['vehicle']);
        }

        if (!empty($criteria['country']))
        {
            $result->andWhere('countryVehicle.country = :country')
                ->setParameter('country', $criteria['country']);
        }

        return $result->getQuery()->getResult();
    }
}
