<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * VehicleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehicleRepository extends EntityRepository
{
    public function search(array $criteria)
    {
        $result = $this->createQueryBuilder('vehicle')
            ->orderBy('vehicle.title');

        $this->initCountrySearchCriteria($result, $criteria);


        return $result;
    }

    private function initCountrySearchCriteria(QueryBuilder $builder, array $criteria)
    {
        if (!empty($criteria['country']))
        {
            $builder->join('vehicle.countryLinks', 'vehicleLink')
                ->andWhere('vehicleLink.country = :country')
                ->setParameter('country', $criteria['country']);
        }

        return $builder;
    }
}
